version: '3.8'
services:
  wso2is:
    image: wso2/wso2is:5.10.0
    container_name: wso2is
    environment:
      - PUID=1000
    ports:
      - 4000:4000
      - 9763:9763
      - 9443:9443
    restart: unless-stopped
